services:
  app:
    restart: always
    env_file:
      - .env
    build:
      context: ./frontend
      dockerfile: ./Dockerfile.dev
    ports:
      - 5050:5050
      - 24678:24678
    volumes:
      - ./frontend/:/usr/src/app
      - /usr/src/app/node_modules
      - ./nginx/dev/:/usr/src/app/nginx/dev/
  nginx:
    restart: always
    build:
      context: ./nginx/dev
    ports:
      - 80:80
      - 443:443

  pb:
    build: backend
    image: pocketbase-custom
    command: /pocketbase serve --dir /app/pb_data --http=pb:8090
    user: ${UID}:${GID}
    expose:
      - 8090
    working_dir: /app
    volumes:
      - ${PWD}/backend:/app
